controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 1000 #  Hz

    arm_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_joint_controller:
      type: forward_command_controller/ForwardCommandController

arm_joint_controller:
  ros__parameters:
  
    joints:
      - link_1_joint
      - link_2_joint
    interface_name: position
    command_interfaces:
      - position 
    state_interfaces:
      - position
      - velocity